# Generated by Django 5.0.14 on 2025-12-27 23:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPortalAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token', models.CharField(max_length=100, unique=True)),
                ('token_expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('can_view_lease', models.BooleanField(default=True)),
                ('can_view_payments', models.BooleanField(default=True)),
                ('can_make_payments', models.BooleanField(default=True)),
                ('can_submit_maintenance', models.BooleanField(default=True)),
                ('can_view_documents', models.BooleanField(default=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_access', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_portal_access',
            },
        ),
        migrations.CreateModel(
            name='TenantPortalSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_token', models.CharField(max_length=100, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('portal_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tenant_portal.tenantportalaccess')),
            ],
            options={
                'db_table': 'tenant_portal_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
