# Generated by Django 5.0.14 on 2025-12-25 21:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('street_address', models.CharField(max_length=255)),
                ('unit_number', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('property_type', models.CharField(choices=[('single_family', 'Single Family'), ('multi_family', 'Multi Family'), ('condo', 'Condo'), ('apartment', 'Apartment'), ('duplex', 'Duplex'), ('triplex', 'Triplex'), ('fourplex', 'Fourplex'), ('commercial', 'Commercial'), ('other', 'Other')], max_length=20)),
                ('is_multi_unit', models.BooleanField(default=False)),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('square_feet', models.PositiveIntegerField(blank=True, null=True)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('has_mortgage', models.BooleanField(default=False)),
                ('mortgage_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mortgage_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mortgage_lender', models.CharField(blank=True, max_length=100)),
                ('insurance_provider', models.CharField(blank=True, max_length=100)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=50)),
                ('insurance_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('insurance_renewal_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('vacant', 'Vacant'), ('maintenance', 'Under Maintenance'), ('listed', 'Listed'), ('sold', 'Sold'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_number', models.CharField(max_length=20)),
                ('floor', models.PositiveIntegerField(blank=True, null=True)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.DecimalField(decimal_places=1, default=1, max_digits=3)),
                ('square_feet', models.PositiveIntegerField(blank=True, null=True)),
                ('market_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('occupied', 'Occupied'), ('vacant', 'Vacant'), ('maintenance', 'Under Maintenance'), ('listed', 'Listed')], default='vacant', max_length=20)),
                ('features', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
            options={
                'db_table': 'units',
                'ordering': ['unit_number'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.unit')),
            ],
            options={
                'db_table': 'property_photos',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner', 'status'], name='properties_owner_i_56c14d_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'state'], name='properties_city_d76a1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('property', 'unit_number')},
        ),
    ]
