# Generated by Django 5.0.14 on 2025-12-27 23:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('lease', 'Lease Agreement'), ('addendum', 'Lease Addendum'), ('application', 'Rental Application'), ('id', 'ID/Verification'), ('receipt', 'Receipt'), ('invoice', 'Invoice'), ('insurance', 'Insurance'), ('inspection', 'Inspection Report'), ('photo', 'Photo'), ('other', 'Other')], default='other', max_length=20)),
                ('file_key', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='leases.lease')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
