# Generated by Django 5.0.14 on 2025-12-27 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('maintenance', '0001_initial'),
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='maintenance_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='maintenance.maintenancerequest'),
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='rental_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='properties.property'),
        ),
        migrations.AddField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='document',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='document',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='properties.unit'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'type'], name='documents_owner_i_9fba69_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['rental_property'], name='documents_rental__75cb4a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['lease'], name='documents_lease_i_f6a702_idx'),
        ),
    ]
