# Generated by Django 5.0.14 on 2025-12-25 21:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('employer', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('previous_address', models.TextField(blank=True)),
                ('previous_landlord_name', models.CharField(blank=True, max_length=200)),
                ('previous_landlord_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('applicant', 'Applicant'), ('approved', 'Approved'), ('active', 'Active'), ('past', 'Past Tenant'), ('rejected', 'Rejected')], default='applicant', max_length=20)),
                ('portal_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('portal_token_expires', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['owner', 'status'], name='tenants_owner_i_bcf8fd_idx'), models.Index(fields=['email'], name='tenants_email_64287b_idx')],
            },
        ),
    ]
