# Generated by Django 5.0.14 on 2025-12-25 21:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('lease_type', models.CharField(choices=[('fixed', 'Fixed Term'), ('month_to_month', 'Month to Month')], default='fixed', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Signature'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('renewed', 'Renewed')], default='draft', max_length=20)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_due_day', models.PositiveIntegerField(default=1)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('security_deposit_paid', models.BooleanField(default=False)),
                ('security_deposit_paid_date', models.DateField(blank=True, null=True)),
                ('late_fee_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent', 'Percentage'), ('daily', 'Daily Amount')], default='fixed', max_length=20)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('late_fee_grace_days', models.PositiveIntegerField(default=5)),
                ('auto_renew', models.BooleanField(default=False)),
                ('renewal_term_months', models.PositiveIntegerField(default=12)),
                ('terminated_date', models.DateField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('rental_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='tenants.tenant')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='properties.unit')),
            ],
            options={
                'db_table': 'leases',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaseAdditionalTenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_responsible_for_rent', models.BooleanField(default=False)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_tenants', to='leases.lease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_leases', to='tenants.tenant')),
            ],
            options={
                'db_table': 'lease_additional_tenants',
            },
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['owner', 'status'], name='leases_owner_i_556403_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['rental_property', 'status'], name='leases_rental__934443_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['tenant', 'status'], name='leases_tenant__efe78a_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['end_date'], name='leases_end_dat_c6aab1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaseadditionaltenant',
            unique_together={('lease', 'tenant')},
        ),
    ]
