# Generated by Django 5.0.14 on 2025-12-25 21:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('late_fee_applied', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_fee_waived', models.BooleanField(default=False)),
                ('late_fee_waived_reason', models.TextField(blank=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_payments', to='leases.lease')),
            ],
            options={
                'db_table': 'rent_payments',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('online', 'Online Payment'), ('other', 'Other')], default='other', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_record', to='transactions.transaction')),
                ('rent_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='payments.rentpayment')),
            ],
            options={
                'db_table': 'payment_records',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['lease', 'status'], name='rent_paymen_lease_i_cfdec6_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['due_date', 'status'], name='rent_paymen_due_dat_10e91f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rentpayment',
            unique_together={('lease', 'due_date')},
        ),
    ]
