# Generated by Django 5.0.14 on 2025-12-27 23:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('tenants', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_payment_method_id', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank_account', 'Bank Account (ACH)')], max_length=20)),
                ('last_four', models.CharField(max_length=4)),
                ('brand', models.CharField(blank=True, max_length=20)),
                ('exp_month', models.IntegerField(blank=True, null=True)),
                ('exp_year', models.IntegerField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_type', models.CharField(blank=True, max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='tenants.tenant')),
            ],
            options={
                'db_table': 'payment_methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaidConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plaid_item_id', models.CharField(max_length=100, unique=True)),
                ('plaid_access_token', models.CharField(max_length=200)),
                ('institution_id', models.CharField(max_length=50)),
                ('institution_name', models.CharField(max_length=200)),
                ('institution_logo', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('cursor', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaid_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plaid_connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaidAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plaid_account_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('official_name', models.CharField(blank=True, max_length=200)),
                ('mask', models.CharField(max_length=4)),
                ('type', models.CharField(choices=[('depository', 'Depository'), ('credit', 'Credit'), ('loan', 'Loan'), ('investment', 'Investment'), ('other', 'Other')], max_length=20)),
                ('subtype', models.CharField(max_length=30)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('available_balance', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('sync_transactions', models.BooleanField(default=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='banking.plaidconnection')),
            ],
            options={
                'db_table': 'plaid_accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StripeAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_account_id', models.CharField(max_length=100, unique=True)),
                ('charges_enabled', models.BooleanField(default=False)),
                ('payouts_enabled', models.BooleanField(default=False)),
                ('details_submitted', models.BooleanField(default=False)),
                ('account_type', models.CharField(default='express', max_length=20)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stripe_accounts',
            },
        ),
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_payment_intent_id', models.CharField(max_length=100, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('stripe_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('application_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('failure_code', models.CharField(blank=True, max_length=100)),
                ('failure_message', models.TextField(blank=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banking.paymentmethod')),
                ('rent_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payments', to='payments.rentpayment')),
            ],
            options={
                'db_table': 'stripe_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaidTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plaid_transaction_id', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=500)),
                ('merchant_name', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plaid_category', models.JSONField(default=list)),
                ('plaid_category_id', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('categorized', 'Categorized'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('pending', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaid_transactions', to='banking.plaidaccount')),
                ('matched_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaid_source', to='transactions.transaction')),
            ],
            options={
                'db_table': 'plaid_transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['account', 'status'], name='plaid_trans_account_2c14ae_idx'), models.Index(fields=['date'], name='plaid_trans_date_df5d02_idx')],
            },
        ),
    ]
